apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-gateway
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/uliseslarraga/link-vault
    targetRevision: feat/gitops
    path: gitops/manifests/argocd-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
