apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-cluster-store
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/uliseslarraga/link-vault
    targetRevision: HEAD
    path: gitops/manifests/eso
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
