apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-config
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.io
spec:
  project: default

  source:
    repoURL: https://github.com/uliseslarraga/link-vault
    targetRevision: feat/gitops
    path: gitops/manifests/karpenter

  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
