apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: link-vault-backend-secret
    creationPolicy: Owner
    template:
      data:
        DATABASE_URL: "postgresql+asyncpg://{{ .username }}:{{ .password }}@link-vault-dev-postgres.cuxc0m8yeddg.us-east-1.rds.amazonaws.com:5432/linkvault"
        DB_USERNAME: "{{ .username }}"
        DB_PASSWORD: "{{ .password }}"
  data:
  - secretKey: username
    remoteRef:
      key: rds!db-685efd46-54aa-41ea-bbaa-2e625b15dca0
      property: username
  - secretKey: password
    remoteRef:
      key: rds!db-685efd46-54aa-41ea-bbaa-2e625b15dca0
      property: password
